
import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Home,ClipboardList,Search,HeartPulse,LineChart}from'lucide-react';import'./styles.css';
const questions=[
{key:'energy',label:'Como você acordou hoje?',options:[['Muito bem',100],['Bem',80],['Mais ou menos',60],['Cansada',35],['Exausta',15]]},
{key:'sleep',label:'Como foi seu sono?',options:[['Muito bom',100],['Bom',80],['Regular',60],['Ruim',35],['Muito ruim',15]]},
{key:'mood',label:'Como está seu humor agora?',options:[['Muito bem',100],['Bem',80],['Oscilando',55],['Sensível',35],['Muito sensível',15]]},
{key:'clarity',label:'Como está sua clareza mental?',options:[['Muito clara',100],['Boa',80],['Regular',60],['Nebulosa',35],['Muito travada',15]]},
{key:'comfort',label:'Como está seu corpo?',options:[['Confortável',100],['Bem',80],['Regular',60],['Desconfortável',35],['Muito desconfortável',15]]},
{key:'hotflashes',label:'Você teve calorões hoje?',options:[['Não',100],['Poucos',75],['Alguns',50],['Muitos',25],['Muito intensos',10]]},
{key:'palpitations',label:'Seu coração acelerou sem motivo claro?',options:[['Não',100],['Uma vez',75],['Poucas vezes',50],['Várias vezes',25],['Muito',10]]},
{key:'stress',label:'Como está sua sobrecarga hoje?',options:[['Baixa',100],['Controlada',80],['Média',60],['Alta',30],['Muito alta',10]]}
];
const signals=[
{title:'Coração acelerado',text:'Palpitações podem assustar. Sono ruim, calorões, cafeína e estresse podem aumentar a percepção dos batimentos. Também existem outras causas, então vale observar o contexto.',help:['Sente-se por alguns minutos','Beba água','Reduza cafeína hoje','Respire lentamente por 1 minuto'],alert:'Procure atendimento imediatamente se houver dor forte no peito, desmaio, falta de ar importante ou sintoma diferente do seu padrão.'},
{title:'Calorão',text:'Calorões são relatados por muitas mulheres na perimenopausa e podem estar ligados à forma como o corpo regula temperatura.',help:['Vá para um local fresco','Use roupas leves','Beba água','Observe gatilhos'],alert:'Procure avaliação se forem muito intensos, frequentes ou vierem com outros sinais preocupantes.'},
{title:'Insônia',text:'O sono pode ficar mais leve e fragmentado nessa fase. Calorões, suor noturno e estresse podem contribuir.',help:['Evite telas à noite','Reduza cafeína no fim do dia','Mantenha o quarto fresco','Não olhe o relógio repetidamente'],alert:'Procure avaliação se persistir por semanas e afetar sua rotina.'},
{title:'Brain Fog',text:'Esquecimentos e falta de foco são relatos comuns. Sono ruim e sobrecarga podem piorar essa sensação.',help:['Faça uma tarefa por vez','Use lembretes simples','Faça pausas curtas','Priorize sono'],alert:'Procure avaliação se for intenso, progressivo ou vier com sintomas neurológicos.'},
{title:'Choro fácil',text:'Mudanças hormonais, cansaço e sobrecarga podem deixar as emoções mais sensíveis. Isso não significa fraqueza.',help:['Não se julgue agora','Faça uma pausa','Converse com alguém de confiança','Reduza estímulos'],alert:'Procure ajuda imediata se houver desesperança intensa ou pensamentos de autoagressão.'},
{title:'Tontura',text:'Tontura tem muitas causas possíveis e não deve ser automaticamente atribuída aos hormônios.',help:['Sente-se','Levante devagar','Hidrate-se','Observe se há jejum ou excesso de calor'],alert:'Procure atendimento se houver desmaio, queda, dor no peito, fraqueza intensa ou sintomas neurológicos.'}
];
function interpret(a,h=0){const energy=a.energy??60,sleep=a.sleep??60,mood=a.mood??60,clarity=a.clarity??60,comfort=Math.round(((a.comfort??60)+(a.hotflashes??80)+(a.palpitations??80))/3),stress=a.stress??60,avg=Math.round((energy+sleep+mood+clarity+comfort)/5);let r={profile:'Oscilação Leve',tone:'yellow',message:'Hoje seu corpo parece pedir um pouco mais de descanso do que velocidade.',priority:'Proteger sua energia.',mission:'Pausar 10 minutos sem celular.',why:'Menos estímulo pode ajudar seu corpo a recuperar ritmo.'};if(avg>=78&&stress>=60)r={profile:h?'Boa Recuperação':'Dia de Equilíbrio',tone:'green',message:'Hoje seu corpo parece responder bem à rotina. Aproveite sem exagerar.',priority:'Manter o que está funcionando.',mission:'Caminhar 15 minutos.',why:'Movimento leve ajuda a preservar energia sem sobrecarregar.'};else if(sleep<45&&energy<50)r={profile:'Corpo Pedindo Pausa',tone:'yellow',message:'Os sinais registrados sugerem que seu sono influenciou bastante sua energia hoje.',priority:'Proteger seu descanso.',mission:'Dormir 30 minutos mais cedo.',why:'Uma pequena antecipação do sono pode ajudar sua recuperação.'};else if((a.hotflashes??100)<45||mood<45)r={profile:'Sensibilidade Hormonal',tone:'orange',message:'Hoje seu corpo demonstra um padrão compatível com maior sensibilidade física e emocional.',priority:'Reduzir estímulos.',mission:'Beber água e fazer uma pausa de 10 minutos.',why:'Hidratação e pausa ajudam a atravessar oscilações com mais segurança.'};else if(stress<40)r={profile:'Sobrecarga',tone:'orange',message:'Seu corpo parece responder ao acúmulo de esforço físico e emocional.',priority:'Diminuir a carga do dia.',mission:'Escolher apenas uma tarefa essencial.',why:'Hoje menos pode ser mais.'};else if(avg<38)r={profile:'Dia Delicado',tone:'red',message:'Hoje vale reduzir expectativas e priorizar autocuidado.',priority:'Cuidar do básico.',mission:'Abrir o SOS se precisar.',why:'Você não precisa resolver tudo agora. Primeiro, cuide do corpo.'};return{...r,indicators:{Energia:energy,Sono:sleep,Humor:mood,'Clareza Mental':clarity,'Conforto Corporal':comfort},avoid:['Excesso de café','Sobrecarga','Pesquisar sintomas repetidamente'],doToday:['Beber mais água','Fazer pequenas pausas','Dormir um pouco mais cedo'],insight:h>=3?'Seu histórico já começa a mostrar padrões pessoais. Continue registrando seus dias.':'Seu primeiro padrão aparecerá após alguns dias de uso.'}}
function Header(){return <header className="header"><div><div className="brand">◉ Radar</div><div className="tagline">Porque entender seu corpo muda tudo.</div></div><div className="pill">Perimenopausa</div></header>}
function Card({children,className=''}){return <section className={'card '+className}>{children}</section>}
function Indicator({label,value}){const d=value>=75?'Seu ponto forte hoje.':value>=55?'Dentro do esperado para hoje.':value>=35?'Merece atenção.':'Prioridade de cuidado hoje.';return <div className="indicator"><div><strong>{label}</strong><span>{d}</span></div><b>{value}%</b></div>}
function App(){const[screen,setScreen]=useState('home'),[answers,setAnswers]=useState({}),[step,setStep]=useState(0),[history,setHistory]=useState(()=>JSON.parse(localStorage.getItem('radarHistory')||'[]')),[reading,setReading]=useState(()=>JSON.parse(localStorage.getItem('radarReading')||'null'));function finish(ans){const r={...interpret(ans,history.length),time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),date:new Date().toLocaleDateString('pt-BR')};setReading(r);localStorage.setItem('radarReading',JSON.stringify(r));const next=[r,...history].slice(0,60);setHistory(next);localStorage.setItem('radarHistory',JSON.stringify(next));setScreen('radar')}return <div className="app"><Header/>{screen==='home'&&<HomeScreen reading={reading} history={history} onStart={()=>{setAnswers({});setStep(0);setScreen('checkin')}} onNav={setScreen}/>} {screen==='checkin'&&<Checkin step={step} setStep={setStep} answers={answers} setAnswers={setAnswers} onFinish={finish}/>} {screen==='radar'&&<RadarScreen reading={reading} onNav={setScreen}/>} {screen==='plan'&&<PlanScreen reading={reading} onNav={setScreen}/>} {screen==='signals'&&<SignalsScreen/>} {screen==='sos'&&<SOSScreen/>} {screen==='progress'&&<ProgressScreen history={history}/>} {screen==='profile'&&<ProfileScreen/>}<BottomNav current={screen} onNav={setScreen}/></div>}
function HomeScreen({reading,history,onStart,onNav}){return <><Card><h1>Bom dia, Juliana.</h1><p>Como seu corpo está hoje?</p><button className="btn" onClick={onStart}>Nova Leitura</button><small>Leva menos de 2 minutos.</small></Card>{reading?<RadarSummary reading={reading} onNav={onNav}/>:<Card><h2>Radar de Hoje</h2><p>Faça sua primeira leitura para ver sua análise.</p><button className="btn secondary" onClick={onStart}>Iniciar agora</button></Card>}<Card><h3>Sua missão de hoje</h3><h2>{reading?.mission||'Fazer sua primeira leitura.'}</h2><p>{reading?.why||'O Radar precisa entender seus sinais de hoje.'}</p><button className="btn gold">Concluir missão</button></Card><div className="grid"><button className="tile" onClick={()=>onNav('signals')}><strong>Entenda</strong><span>Por que o sono influencia sua energia?</span></button><button className="tile" onClick={()=>onNav('progress')}><strong>Evolução</strong><span>{history.length} leituras acompanhadas</span></button></div></>}
function RadarSummary({reading,onNav}){return <Card><div className={'status '+reading.tone}>{reading.profile}</div><h2>Radar de Hoje</h2><p className="muted">Última análise: hoje às {reading.time}</p><p>{reading.message}</p>{Object.entries(reading.indicators).map(([k,v])=><Indicator key={k} label={k} value={v}/>) }<button className="btn secondary" onClick={()=>onNav('plan')}>Ver Plano do Dia</button></Card>}
function Checkin({step,setStep,answers,setAnswers,onFinish}){const q=questions[step],sel=answers[q.key];function next(){if(sel===undefined)return;step<questions.length-1?setStep(step+1):onFinish(answers)}return <Card className="checkin"><div className="progress"><span style={{width:`${((step+1)/questions.length)*100}%`}}/></div><p className="muted">Pergunta {step+1} de {questions.length}</p><h2>{q.label}</h2><div className="options">{q.options.map(([l,v])=><button key={l} className={sel===v?'option active':'option'} onClick={()=>setAnswers({...answers,[q.key]:v})}>{l}</button>)}</div><button className="btn" disabled={sel===undefined} onClick={next}>Continuar</button></Card>}
function RadarScreen({reading,onNav}){if(!reading)return <Card><h2>Faça sua primeira leitura.</h2></Card>;return <><RadarSummary reading={reading} onNav={onNav}/><Card><h3>Prioridade</h3><h2>{reading.priority}</h2></Card><Card><h3>O que ajuda hoje</h3>{reading.doToday.map(x=><p key={x}>✓ {x}</p>)}</Card><Card className="soft"><h3>Evite hoje</h3>{reading.avoid.map(x=><p key={x}>• {x}</p>)}</Card></>}
function PlanScreen({reading,onNav}){if(!reading)return <Card><h2>Faça sua leitura primeiro.</h2></Card>;return <><Card><h1>{reading.mission}</h1><p>{reading.why}</p></Card><Card><h3>Faça hoje</h3>{reading.doToday.map(x=><p key={x}>✓ {x}</p>)}</Card><Card className="soft"><h3>Vale lembrar</h3><p>O Radar organiza sinais. Ele não faz diagnóstico nem substitui acompanhamento médico.</p></Card><button className="btn" onClick={()=>onNav('home')}>Voltar ao Radar</button></>}
function SignalsScreen(){const[open,setOpen]=useState(signals[0]);return <><Card><h1>Entenda um Sinal</h1><p>Escolha um sinal para entender sem pânico.</p><div className="chips">{signals.map(s=><button key={s.title} onClick={()=>setOpen(s)}>{s.title}</button>)}</div></Card><Card><h2>{open.title}</h2><p>{open.text}</p></Card><Card><h3>O que pode ajudar hoje</h3>{open.help.map(x=><p key={x}>✓ {x}</p>)}</Card><Card className="soft"><h3>Quando procurar ajuda</h3><p>{open.alert}</p></Card></>}
function SOSScreen(){const ps={'Coração acelerado':['Primeiro, sente-se. Você não precisa resolver tudo ao mesmo tempo.','Observe se há dor no peito, desmaio ou falta de ar importante. Se houver, procure atendimento imediatamente.'],'Calorão intenso':['Vá para um local fresco, retire uma camada de roupa e beba água.','Se for muito intenso, persistente ou diferente do seu padrão, procure avaliação.'],'Crise de choro':['Você não precisa controlar isso agora. Primeiro, acolha o que está sentindo.','Se houver sofrimento intenso ou pensamentos de autoagressão, procure ajuda imediatamente.'],'Acordei de madrugada':['Evite olhar o relógio e não pegue o celular. Mantenha pouca luz.','Se isso se repetir por semanas e afetar sua rotina, converse com um profissional.']};const[p,setP]=useState(null);return <>{!p&&<><Card className="soft"><h1>Respire.</h1><p>Vamos dar um passo de cada vez.</p></Card><Card><h2>O que está acontecendo agora?</h2><div className="options">{Object.keys(ps).map(k=><button className="option" key={k} onClick={()=>setP(k)}>{k}</button>)}</div></Card></>}{p&&<><Card><h2>{p}</h2><p>{ps[p][0]}</p></Card><Card className="soft"><h3>Segurança</h3><p>{ps[p][1]}</p></Card><button className="btn" onClick={()=>setP(null)}>Ver outros protocolos</button></>}</>}
function ProgressScreen({history}){return <><Card><h1>Minha Evolução</h1><p>Você já completou {history.length} leituras.</p></Card><Card><h3>Principal padrão</h3><p>{history.length>=3?'Seu histórico já começa a mostrar tendências. Continue registrando para aumentar a precisão.':'O primeiro padrão aparecerá após alguns dias de uso.'}</p></Card>{history.map((h,i)=><Card key={i}><strong>{h.date}</strong><p>{h.profile}</p><p>{h.message}</p></Card>)}</>}
function ProfileScreen(){return <Card><h1>Perfil</h1><p>Configurações, privacidade e preferências do Radar.</p></Card>}
function BottomNav({current,onNav}){const items=[['home','Início',Home],['checkin','Leitura',ClipboardList],['signals','Sinais',Search],['sos','SOS',HeartPulse],['progress','Evolução',LineChart]];return <nav className="bottom">{items.map(([k,l,I])=><button key={k} className={current===k?'active':''} onClick={()=>onNav(k)}><I size={18}/><span>{l}</span></button>)}</nav>}
createRoot(document.getElementById('root')).render(<App/>);
