export function interpretRadar(answers, historyLength=0){
const energy=answers.energy??answers.wake??60,sleep=answers.sleep??60,mood=answers.mood??60,clarity=Math.round(((answers.clarity??60)+(answers.brainFog??100))/2),comfort=Math.round(((answers.comfort??60)+(answers.hotflashes??100)+(answers.palpitations??100))/3),stress=answers.stress??60;
const average=Math.round((energy+sleep+mood+clarity+comfort)/5);
let result={profile:"Oscilação Leve",tone:"yellow",message:"Hoje seu corpo parece pedir um pouco mais de descanso do que velocidade.",priority:"Proteger sua energia.",mission:"Pausar 10 minutos sem celular.",why:"Menos estímulo pode ajudar seu corpo a recuperar ritmo.",insight:"Seu primeiro padrão aparecerá após alguns dias de uso."};
if(average>=78&&stress>=60)result={profile:historyLength?"Boa Recuperação":"Dia de Equilíbrio",tone:"green",message:"Hoje seu corpo parece responder bem à rotina. Aproveite sem exagerar.",priority:"Manter o que está funcionando.",mission:"Caminhar 15 minutos.",why:"Movimento leve ajuda a preservar energia sem sobrecarregar.",insight:"Dias estáveis ajudam o Radar a entender o que funciona para você."};
else if(sleep<45&&energy<55)result={profile:"Corpo Pedindo Pausa",tone:"yellow",message:"Os sinais registrados sugerem que seu sono influenciou bastante sua energia hoje.",priority:"Proteger seu descanso.",mission:"Dormir 30 minutos mais cedo.",why:"Uma pequena antecipação do sono pode ajudar sua recuperação.",insight:"Sono e energia costumam caminhar juntos. Observe esse padrão nos próximos dias."};
else if((answers.hotflashes??100)<45||mood<45||(answers.palpitations??100)<45)result={profile:"Sensibilidade Hormonal",tone:"orange",message:"Hoje seu corpo demonstra um padrão compatível com maior sensibilidade física e emocional.",priority:"Reduzir estímulos.",mission:"Beber água e fazer uma pausa de 10 minutos.",why:"Hidratação e pausa ajudam a atravessar oscilações com mais segurança.",insight:"Registrar calorões, sono e humor pode revelar gatilhos importantes."};
else if(stress<40)result={profile:"Sobrecarga",tone:"orange",message:"Seu corpo parece responder ao acúmulo de esforço físico e emocional.",priority:"Diminuir a carga do dia.",mission:"Escolher apenas uma tarefa essencial.",why:"Hoje menos pode ser mais.",insight:"Sobrecarga repetida pode aparecer no corpo antes de aparecer na agenda."};
else if(average<38)result={profile:"Dia Delicado",tone:"red",message:"Hoje vale reduzir expectativas e priorizar autocuidado.",priority:"Cuidar do básico.",mission:"Abrir o SOS se precisar.",why:"Você não precisa resolver tudo agora. Primeiro, cuide do corpo.",insight:"Dias delicados merecem cuidado, não cobrança."};
return{...result,indicators:{Energia:energy,Sono:sleep,Humor:mood,"Clareza Mental":clarity,"Conforto Corporal":comfort},doToday:getActions(result.profile),avoid:getAvoid(result.profile),updatedAt:new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}}
function getActions(p){return({"Dia de Equilíbrio":["Manter hidratação","Movimento leve","Preservar o sono"],"Boa Recuperação":["Repetir o que funcionou ontem","Evitar exageros","Registrar como se sente hoje"],"Oscilação Leve":["Beber mais água","Fazer pequenas pausas","Dormir um pouco mais cedo"],"Corpo Pedindo Pausa":["Reduzir estímulos","Evitar telas antes de dormir","Fazer uma pausa real"],"Sensibilidade Hormonal":["Ambiente fresco","Hidratação","Reduzir cafeína"],"Sobrecarga":["Diminuir agenda","Escolher uma tarefa essencial","Pausa sem celular"],"Dia Delicado":["Abrir o SOS se precisar","Cuidar do básico","Procurar apoio se necessário"]}[p]||["Beber mais água","Fazer pequenas pausas","Dormir um pouco mais cedo"])}
function getAvoid(p){return({"Dia de Equilíbrio":["Exagerar por estar bem","Dormir tarde","Ignorar sinais sutis"],"Boa Recuperação":["Acelerar demais","Compensar atrasos","Pular refeições"],"Oscilação Leve":["Excesso de café","Sobrecarga","Pesquisar sintomas repetidamente"],"Corpo Pedindo Pausa":["Telas até tarde","Agenda cheia","Cobrança excessiva"],"Sensibilidade Hormonal":["Ambientes muito quentes","Cafeína em excesso","Álcool hoje"],"Sobrecarga":["Assumir mais tarefas","Responder no impulso","Ignorar cansaço"],"Dia Delicado":["Se isolar totalmente","Se culpar","Adiar atendimento se houver sinais de alerta"]}[p]||["Excesso de café","Sobrecarga","Pesquisar sintomas repetidamente"])}
