export function analyzeContext(text=""){
 const t=text.trim().toLowerCase();
 if(!t)return{type:"none",label:"Sem contexto adicional",modifier:0,note:""};
 if(/gripad|resfri|febre|tosse|garganta|virose|doente/.test(t))return{type:"illness",label:"Recuperação física",modifier:-12,note:"Você relatou mal-estar ou sintomas gripais. A leitura prioriza recuperação e evita atribuir tudo à transição hormonal."};
 if(/briguei|discuss|conflito|marido|filho|família|familia|reunião|reuniao|trabalho|preocupada|luto/.test(t))return{type:"emotional",label:"Contexto emocional",modifier:-8,note:"O que aconteceu hoje pode influenciar sono, humor, energia e percepção dos sintomas."};
 if(/menstru|sangramento|cólica|colica|tpm/.test(t))return{type:"cycle",label:"Contexto do ciclo",modifier:-5,note:"O momento do ciclo pode influenciar dor, humor, retenção e energia."};
 if(/dormi|sono|madrugada|insônia|insonia/.test(t))return{type:"sleep",label:"Noite fora do padrão",modifier:-7,note:"Você relatou um contexto de sono que pode influenciar boa parte dos sinais de hoje."};
 return{type:"free",label:"Contexto informado por você",modifier:-3,note:"A Radar considerou o que você contou ao interpretar seus sinais."}
}
export function buildReading(a,contextText,bodyPhrase,history=[]){
 const context=analyzeContext(contextText);
 const sleep=a.sleep??70,energy=Math.round(((a.energy??70)+(a.wake??70))/2),heat=a.heat??80,pain=a.pain??80,clarity=Math.round(((a.clarity??75)+(a.memory??75))/2),mood=Math.round(((a.mood??75)+(a.stress??75))/2);
 const dimensions={Sono:clamp(sleep+context.modifier),Energia:clamp(energy+context.modifier),Calorões:heat,Dor:pain,"Clareza mental":clarity,Humor:mood};
 const frequency=clamp(Math.round(weighted(dimensions)));
 const ranked=Object.entries(dimensions).sort((a,b)=>a[1]-b[1]);
 const topSignals=ranked.slice(0,3).map(([label,value])=>({label,value,explanation:explain(label,value,dimensions,context)}));
 let profile=frequency>=82?"Boa recuperação":frequency>=66?"Estabilidade com oscilações":frequency>=48?"Sobrecarga moderada":"Atenção ampliada";
 let tone=frequency>=82?"green":frequency>=66?"yellow":frequency>=48?"orange":"red";
 let bodySays=bodyPhrase?.trim()||defaultBodySays(ranked[0][0],frequency);
 let interpretation=buildInterpretation(ranked,context,frequency);
 let prescriptionKey=pickPrescription(ranked[0][0],context);
 if(context.type==="illness"){profile="Recuperação física";tone="orange";prescriptionKey="recovery"}
 const mission=missionFor(context,ranked,dimensions),forecast=forecastFor(dimensions,context),nutrition=nutritionFor(context,pain,sleep,heat);
 const discovered=buildMemoryInsights([ {dimensions}, ...history])[0]||"A Radar precisa de mais alguns registros para revelar relações pessoais.";
 return{frequency,profile,tone,bodySays,interpretation,dimensions,topSignals,context,prescriptionKey,mission,nutrition,forecast,bodyPhrase,discovered,updatedAt:new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}),date:new Date().toLocaleDateString("pt-BR")}}
function weighted(d){return d.Sono*.2+d.Energia*.2+d.Calorões*.14+d.Dor*.14+d["Clareza mental"]*.16+d.Humor*.16}
function explain(label,value,d,c){const level=value<36?"foi o sinal mais intenso":value<56?"pediu atenção":value<76?"oscilou levemente":"permaneceu estável";const links={Sono:"e pode repercutir em energia, humor e clareza ao longo do dia.",Energia:"e sugere preservar esforço para o que realmente importa.",Calorões:"e merece observação de horário, intensidade e possíveis gatilhos.",Dor:"e indica que movimento e carga precisam respeitar seus limites.",["Clareza mental"]:"e pode deixar decisões, memória e foco mais exigentes.",Humor:"e pode reduzir sua tolerância a estímulos e cobranças."};return `${label} ${level} ${links[label]}`}
function defaultBodySays(label,frequency){if(frequency>=82)return"Hoje posso manter o que está funcionando.";const map={Sono:"Hoje preciso proteger meu descanso.",Energia:"Hoje preciso gastar energia com intenção.",Calorões:"Hoje preciso reduzir gatilhos.",Dor:"Hoje preciso de cuidado no corpo.",["Clareza mental"]:"Hoje preciso de uma coisa por vez.",Humor:"Hoje preciso baixar o volume do dia."};return map[label]}
function buildInterpretation(ranked,context,frequency){const a=ranked[0][0].toLowerCase(),b=ranked[1][0].toLowerCase();let text=frequency>=82?`Seus registros mostram boa estabilidade geral, com ${a} e ${b} como os sinais relativamente mais sensíveis.`:`A combinação entre ${a} e ${b} explica por que o dia pode parecer mais exigente. A prioridade não é render mais, mas reduzir atrito e observar como esses sinais evoluem.`;if(context.type!=="none")text+=` O contexto informado também entrou nessa leitura.`;return text}
function pickPrescription(label,c){if(c.type==="illness")return"recovery";return({Sono:"sleep",Energia:"recovery",Calorões:"heat",Dor:"pain",["Clareza mental"]:"focus",Humor:"calm"})[label]||"calm"}
function missionFor(c,ranked,d){if(c.type==="illness")return["Hidratar-se ao longo do dia","Reduzir esforço sem culpa","Observar sinais de piora"];const out=[];for(const [k] of ranked){if(k==="Sono"&&!out.includes("Proteger o sono desta noite"))out.push("Proteger o sono desta noite");if(k==="Energia"&&!out.includes("Escolher uma prioridade principal"))out.push("Escolher uma prioridade principal");if(k==="Calorões"&&!out.includes("Manter água e ambiente fresco por perto"))out.push("Manter água e ambiente fresco por perto");if(k==="Dor"&&!out.includes("Trocar intensidade por mobilidade leve"))out.push("Trocar intensidade por mobilidade leve");if(k==="Clareza mental"&&!out.includes("Fazer uma tarefa por vez"))out.push("Fazer uma tarefa por vez");if(k==="Humor"&&!out.includes("Adiar respostas no impulso"))out.push("Adiar respostas no impulso");if(out.length===3)break}return out}
function forecastFor(d,c){const i=[];if(d.Sono<56||d.Energia<56)i.push("A energia pode cair no meio da tarde; preserve uma janela de descanso ou tarefas leves.");if(d.Calorões<56)i.push("Ambientes quentes, álcool, café ou estresse podem coincidir com maior desconforto hoje.");if(d.Humor<56)i.push("Sua tolerância a ruído, pressa e demandas pode ficar menor no fim do dia.");if(d["Clareza mental"]<56)i.push("Decisões complexas podem exigir mais tempo; registre o próximo passo em vez de depender da memória.");if(!i.length)i.push("A tendência é de estabilidade, desde que você preserve o ritmo que funcionou até aqui.");if(c.type==="illness")i.unshift("O contexto físico pode pesar mais do que o padrão hormonal hoje.");return i.slice(0,3)}
function nutritionFor(c,p,s,h){if(c.type==="illness")return{headline:"Mais hidratação e refeições simples",needs:["Água e bebidas sem cafeína","Proteína de fácil digestão","Frutas e legumes","Refeições menores"],reduce:["Álcool","Ultraprocessados","Excesso de açúcar"],why:"Você relatou mal-estar ou sintomas gripais."};if(p<55)return{headline:"Mais alimentos de padrão anti-inflamatório",needs:["Peixes ricos em ômega-3","Azeite de oliva","Folhas verdes","Frutas vermelhas"],reduce:["Ultraprocessados","Excesso de açúcar","Álcool"],why:"Dor ou rigidez apareceu como ponto de atenção."};if(s<55)return{headline:"Mais leveza no fim do dia",needs:["Proteína distribuída nas refeições","Aveia","Kiwi","Castanhas"],reduce:["Cafeína após 14h","Jantar pesado","Excesso de açúcar à noite"],why:"Seu sono apareceu como prioridade."};if(h<55)return{headline:"Mais hidratação e menos gatilhos",needs:["Água","Iogurte natural ou kefir","Linhaça moída","Vegetais verdes"],reduce:["Álcool","Pimenta em excesso","Cafeína em excesso"],why:"A leitura indicou maior sensibilidade a calorões."};return{headline:"Mais proteína e energia estável",needs:["Ovos","Feijão ou lentilha","Abacate","Folhas verde-escuras"],reduce:["Pular refeições","Excesso de açúcar","Cafeína no fim do dia"],why:"A estratégia de hoje é manter energia mais estável."}}
export function buildMemoryInsights(history=[]){if(history.length<3)return["Ainda não há registros suficientes para afirmar um padrão. Continue observando sem transformar o check-in em obrigação."];const rows=history.filter(h=>h?.dimensions);if(rows.length<3)return["Ainda não há registros suficientes para afirmar um padrão."];const avg=k=>Math.round(rows.reduce((s,r)=>s+(r.dimensions[k]??50),0)/rows.length);const lowSleep=rows.filter(r=>(r.dimensions.Sono??100)<56);const insights=[];if(lowSleep.length>=2){const e=Math.round(lowSleep.reduce((s,r)=>s+(r.dimensions.Energia??50),0)/lowSleep.length),c=Math.round(lowSleep.reduce((s,r)=>s+(r.dimensions["Clareza mental"]??50),0)/lowSleep.length);insights.push(`Nos dias de sono mais baixo, energia ficou em média em ${e} e clareza mental em ${c}.`)}const lows=Object.keys(rows[0].dimensions).map(k=>[k,avg(k)]).sort((a,b)=>a[1]-b[1]);insights.push(`${lows[0][0]} foi o sinal mais sensível no período, com média de ${lows[0][1]}.`);if(rows.length>=5){const recent=rows.slice(0,3).reduce((s,r)=>s+(r.frequency??weighted(r.dimensions)),0)/3,older=rows.slice(3,6).reduce((s,r)=>s+(r.frequency??weighted(r.dimensions)),0)/Math.min(3,rows.slice(3,6).length);if(Number.isFinite(older))insights.push(recent>older+5?"Os registros mais recentes mostram melhora em relação aos anteriores.":recent<older-5?"Os registros mais recentes mostram uma queda que vale acompanhar.":"Os registros recentes permanecem relativamente estáveis.")}return insights.slice(0,3)}
function clamp(v){return Math.max(0,Math.min(100,Math.round(v)))}
